apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serving-core-v0_22_0.yaml
- net-istio-v0_22_0.yaml
- eventing-core-v0_22_0.yaml # Eventing is optional

images:
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  digest: sha256:787a95d0afad014296f4a8e8a7620053354d4f8d561e8ab6a0451bed112f92c2
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  digest: sha256:587952c8786459b60e260d8b3e99f9494ec388f02565b669d9a12e1c66b51ff0
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  digest: sha256:f6c58671dcdc13f5d257d6049d5d802b5fbdc37d9e60cdc34ef026e5df92d902
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  digest: sha256:d322e4fe634f5eb422b618ee2748c511c933f6b85c1773210e495ea6d695aff1
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  digest: sha256:3c29118e9736ead1b514877037b8577f588711343e42e64f993b10bd075a7657
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  digest: sha256:504e97c906a520f649a878f5b4e3cb72cf7ee8a97165023af72abfad1b70855b
# Eventing is optional
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/eventing/cmd/controller
  digest: sha256:0b06f0760ec9ba9d812e5f05c641be83d11282450ef6f9cd46a4e8a99821ab0a
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/eventing/cmd/webhook
  digest: sha256:5edf99c01662442e755179004634f7d77f996f91325535f64d3c79effd35f51a
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/mtping
  newName: gcr.io/knative-releases/knative.dev/eventing/cmd/mtping
  digest: sha256:6b284a9ef64089873ca1b43342ef98719247bedb7abcd5497b3b05cb2f884775
